### ISSUE TITLE
need help, l4d2 keep restarting

### ISSUE THREAD

**Issue by Lxeon** [startersclan/docker-sourceservers#22]
im using docker-compose.yml, here is my setting
![图片](https://user-images.githubusercontent.com/28784869/128608169-539ff310-fe53-4e09-82f0-95014f46cbb8.png)

when i start this container, its keep restarting
![图片](https://user-images.githubusercontent.com/28784869/128608195-c9b5ddf7-c0a6-4262-a59f-dbb20c06dda5.png)

and it cant be exec
![图片](https://user-images.githubusercontent.com/28784869/128608216-6df359fd-0270-48f6-9e05-8955981d122c.png)

is there any solution?

**Comment by joeltimothyoh** [comment]
Try this:

```
$ docker run -it -p 27015:27015/udp sourceservers/left4dead2:latest 'srcds_linux -game left4dead2 -port 27015 +map “c2m1_highway coop”’
```

[The entrypoint is `bash -c`](https://github.com/startersclan/docker-sourceservers/blob/cb9f2ec9fa3c303ed00ab6b6a19ee02324ae74f7/README.md). So add the game startup command line `srcds_linux <your -params and +cvars>` within a single string as the last argument of the `docker run` command. The same idea is applied to `docker-compose.yml`:

```
l4d2:
  image: sourceservers/left4dead2:latest
  container_name: l4d2
  restart: always
  ports:
    - 27015:27015
    - 27015:27015/udp
  #volumes:
  command: “srcds_linux -game left4dead2 -port 27015 +map “c2m1_highway coop”
```

I haven’t tested the above code but will do so when I get back. @Lxeon

**Comment by Lxeon** [comment]
> 
> 
> Try this:
> 
> ```
> $ docker run -it -p 27015:27015/udp sourceservers/left4dead2:latest 'srcds_linux -game left4dead2 -port 27015 +map “c2m1_highway coop”’
> ```
> 
> [The entrypoint is `bash -c`](https://github.com/startersclan/docker-sourceservers/blob/cb9f2ec9fa3c303ed00ab6b6a19ee02324ae74f7/README.md). So add the game startup command line `srcds_linux <your -params and +cvars>` within a single string as the last argument of the `docker run` command. The same idea is applied to `docker-compose.yml`:
> 
> ```
> l4d2:
>   image: sourceservers/left4dead2:latest
>   container_name: l4d2
>   restart: always
>   ports:
>     - 27015:27015
>     - 27015:27015/udp
>   #volumes:
>   command: ‘srcds_linux -game left4dead2 -port 27015 +map “c2m1_highway coop”’
> ```
> 
> I haven’t tested the above code but will do so when I get back. @Lxeon

`docker run -it -p 27015:27015/udp sourceservers/left4dead2:latest 'srcds_linux -game left4dead2 -port 27015 +map "c2m1_highway coop"'
`
this one its work. 

but if using docker-compose its still keep restarting
![图片](https://user-images.githubusercontent.com/28784869/128609551-de1da08e-21fa-40eb-810b-79b5047798e0.png)

`  l4d2:
    image: sourceservers/left4dead2:latest
    container_name: l4d2
    restart: always
    ports:
      - 27015:27015
      - 27015:27015/udp
    #volumes:
    command: 'srcds_linux -game left4dead2 -port 27015 +map "c2m1_highway coop"'
`
here its logs:
![图片](https://user-images.githubusercontent.com/28784869/128609518-c427574c-436e-4067-9fee-35c5b61f63ac.png)

**Comment by joeltimothyoh** [comment]
@Lxeon Looks like `docker-compose.yml` is missing the `-it` options of `docker run`.

```
    …
    stdin: true
    tty: true
```

**Comment by Lxeon** [comment]
> 
> 
> @Lxeon Looks like `docker-compose.yml` is missing the `-it` options of `docker run`.
> 
> ```
>     …
>     stdin_open: true
>     tty: true
> ```

its no work...
![图片](https://user-images.githubusercontent.com/28784869/128610035-adbfb0ef-847f-4986-a233-9ce7c2706120.png)


![图片](https://user-images.githubusercontent.com/28784869/128610050-dbae2616-9fac-4b26-868c-63855b431055.png)


> 
> 
> @Lxeon Looks like `docker-compose.yml` is missing the `-it` options of `docker run`.
> 
> ```
>     …
>     stdin_open: true
>     tty: true
> ```

here we go, i find what it happen.

just add -c before command
```
  l4d2:
    image: sourceservers/left4dead2:latest
    container_name: l4d2
    restart: always
    ports:
      - 27015:27015
      - 27015:27015/udp
    #stdin_open: true
    #tty: true
    #volumes:
    command: -c 'srcds_linux -game left4dead2 -port 27015 +map "c2m1_highway coop"'
```

no need stdin_open and tty 😂

thanks you for help~~~

**Comment by Lxeon** [comment]
> 
> 
> @Lxeon Looks like `docker-compose.yml` is missing the `-it` options of `docker run`.
> 
> ```
>     …
>     stdin_open: true
>     tty: true
> ```

i find how it work, we should add '-c' before command
```
  l4d2:
    image: sourceservers/left4dead2:latest
    container_name: l4d2
    restart: always
    ports:
      - 27015:27015
      - 27015:27015/udp
    #stdin_open: true
    #tty: true
    #volumes:
    command: -c 'srcds_linux -game left4dead2 -port 27015 +map "c2m1_highway coop"'
```

no need stdin_open and tty 😂

thanks you for help~~~~~~~~
